version: '3'

services:
  myDB:
    image: mysql:9.0.1
    container_name: mysql-database
    restart: always
    environment:
      - MYSQL_DATABASE=course-db
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - ./my-db:/var/lib/mysql
volumes:
  my-db: 
    
    